language: python

services:
  - docker

before_script:
  - cp .gitignore .dockerignore
  - echo '.git' >> .dockerignore

script:
  - docker build -t $DOCKER_REPOSITORY:python .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_REPOSITORY

branches:
  only:
    - master